name: thinktandem
proxy:
  nginx:
    - thinktandem.lndo.site
services:
  cli:
    type: node:6
    build:
      - cd $LANDO_MOUNT && npm install
      - cd $LANDO_MOUNT && npm install -g bower
      - cd $LANDO_MOUNT && npm install -g grunt-cli
      - cd $LANDO_MOUNT && bower install
      - cd $LANDO_MOUNT && grunt build
  appserver:
    type: php:7.1
    via: nginx
    webroot: build
tooling:
  node:
    service: cli
  npm:
    service: cli
  grunt:
    cmd: /app/node_modules/.bin/grunt
    service: cli
  bower:
    cmd: /app/node_modules/.bin/bower
    service: cli
