language: node_js
node_js:
  - '6'
services:
  - docker

before_install:
  - sudo apt-get -y update
  - sudo apt-get -y install cgroup-bin curl
  - curl -fsSL -o /tmp/lando.deb https://github.com/lando/lando/releases/download/v3.0.0-beta.35/lando-v3.0.0-beta.35.deb
  - sudo dpkg -i /tmp/lando.deb
  - lando version

script:
  - lando npm install
  - lando bower install -y
  - lando grunt build
  - lando start -- -v
  - lando grunt test
