https://www.{default}/:
  type: redirect
  to: "https://{default}/"
http://{default}/:
  type: redirect
  to: https://{default}/
https://{default}/:
  type: upstream
  upstream: app:http
  cache:
    enabled: true
  ssi:
    enabled: false
